name: build

on: [release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, linux-latest]
    defaults:
      run:
        working-directory: ./TouchPortalYTMusic

    steps:
      - uses: actions/checkout@v3
      - name: Run build on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
        run: pip3 install https://github.com/KillerBOSS2019/TouchPortal-API/archive/refs/heads/tppdoc.zip
      - name: Build
        run: |
          python3 build.py
      - uses: actions/upload-artifact@v3
        with:
          name: *.tpp

      
